{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apptentiveAssertionHandler"},{"kind":"text","text":": ("},{"kind":"attribute","text":"@autoclosure "},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> ()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This can be overriden, for example:"}]},{"type":"codeListing","syntax":null,"code":["apptentiveAssertionHandler = { message, file, line in","    print(\"\\(file):\\(line): Apptentive critical error: \\(message())\")","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/apptentivekit\/apptentiveassertionhandler"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.apptentive.Apptentive\/documentation\/ApptentiveKit\/apptentiveAssertionHandler","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method to call when a critical error occurs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apptentiveAssertionHandler"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> ()"}],"title":"apptentiveAssertionHandler","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"s:13ApptentiveKit26apptentiveAssertionHandleryySSyXK_s12StaticStringVSutcvp","modules":[{"name":"ApptentiveKit"}]},"hierarchy":{"paths":[["doc:\/\/com.apptentive.Apptentive\/documentation\/ApptentiveKit"]]},"references":{"doc://com.apptentive.Apptentive/documentation/ApptentiveKit/apptentiveAssertionHandler":{"role":"symbol","title":"apptentiveAssertionHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apptentiveAssertionHandler"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> ()"}],"abstract":[{"type":"text","text":"The method to call when a critical error occurs."}],"identifier":"doc:\/\/com.apptentive.Apptentive\/documentation\/ApptentiveKit\/apptentiveAssertionHandler","kind":"symbol","type":"topic","url":"\/documentation\/apptentivekit\/apptentiveassertionhandler"},"doc://com.apptentive.Apptentive/documentation/ApptentiveKit":{"role":"collection","title":"ApptentiveKit","abstract":[],"identifier":"doc:\/\/com.apptentive.Apptentive\/documentation\/ApptentiveKit","kind":"symbol","type":"topic","url":"\/documentation\/apptentivekit"}}}